import time
import datetime
import pytz
# <div class="cell">东方航空</div>
OZ = {"MU": "东方航空",
      "HO": "吉祥航空",
      "8L": "祥鹏航空",
      "GS": "天津航空",
      "3U": "四川航空",
      "FM": "上海航空",
      "SC": "山东航空",
      "G5": "华夏航空",
      "JD": "首都航空",
      "JR": "幸福航空",
      "HU": "海南航空",
      "ZH": "深圳航空",
      "MF": "厦门航空",
      "PN": "西部航空",
      "NS": "河北航空",
      "VD": "河南航空",
      "KN": "联合航空",
      "BK": "欧凯航空",
      "EU": "成都航空",
      "9C": "春秋航空",
      "KY": "昆明航空",
      "TV": "西藏航空",
      "OQ": "重庆航空",
      "GJ": "长龙航空",
      "YI": "云南英安航空",
      "DZ": "东海航空",
      "QW": "青岛航空",
      "DR": "瑞丽航空",
      "FU": "福州航空",
      "Y8": "扬子江航空",
      "AQ": "九元航空",
      "GX": "北部航空",
      "RY": "江西航空",
      "A6": "红土航空",
      "9H": "长安航空",
      "GT": "桂林航空",
      "CA": "中国国航",
      "LT": "龙江航空",
      "CZ": "南方航空",
      "GI": "龙浩航空",
      "ZG": "尊翔航空",
      "HZ": "中航航空",
      "YA": "华彬亚盛", }


class ListDetailExtractData(object):

    def __init__(self):
        pass

    @staticmethod
    def read_excel_to_dict():
        item = [
            # {'city': '阿勒泰', 'ThreeCode': 'AAT', 'Code': 175},
            # {'city': '阿克苏', 'ThreeCode': 'AKU', 'Code': 173},
            # {'city': '鞍山', 'ThreeCode': 'AOG', 'Code': 178},
            # {'city': '安庆', 'ThreeCode': 'AQG', 'Code': 177},
            # {'city': '安顺', 'ThreeCode': 'AVA', 'Code': 179},
            # {'city': '阿拉善左旗', 'ThreeCode': 'AXF', 'Code': 21269},
            # {'city': '阿里', 'ThreeCode': 'NGQ', 'Code': 97},
            # {'city': '阿拉善右旗', 'ThreeCode': 'RHT', 'Code': 21863},
            # {'city': '阿尔山', 'ThreeCode': 'YIE', 'Code': 1658},
            # {'city': '巴中', 'ThreeCode': 'BZX', 'Code': 3966},
            # {'city': '百色', 'ThreeCode': 'AEB', 'Code': 1140},
            # {'city': '包头', 'ThreeCode': 'BAV', 'Code': 141},
            # {'city': '毕节', 'ThreeCode': 'BFJ', 'Code': 22031},
            # {'city': '北海', 'ThreeCode': 'BHY', 'Code': 189},
            {'city': '北京', 'ThreeCode': 'BJS', 'Code': 1},
            # {'city': '博乐', 'ThreeCode': 'BPL', 'Code': 2548},
            # {'city': '保山', 'ThreeCode': 'BSD', 'Code': 197},
            # {'city': '白城', 'ThreeCode': 'DBC', 'Code': 1116},
            # {'city': '布尔津', 'ThreeCode': 'KJI', 'Code': 3326},
            # {'city': '白山', 'ThreeCode': 'NBS', 'Code': 199},
            # {'city': '巴彦淖尔', 'ThreeCode': 'RLK', 'Code': 3887},
            # {'city': '昌都', 'ThreeCode': 'BPX', 'Code': 575},
            # {'city': '承德', 'ThreeCode': 'CDE', 'Code': 562},
            # {'city': '常德', 'ThreeCode': 'CGD', 'Code': 201},
            {'city': '长春', 'ThreeCode': 'CGQ', 'Code': 158},
            # {'city': '朝阳', 'ThreeCode': 'CHG', 'Code': 211},
            # {'city': '赤峰', 'ThreeCode': 'CIF', 'Code': 202},
            # {'city': '长治', 'ThreeCode': 'CIH', 'Code': 137},
            {'city': '重庆', 'ThreeCode': 'CKG', 'Code': 4},
            {'city': '长沙', 'ThreeCode': 'CSX', 'Code': 206},
            {'city': '成都', 'ThreeCode': 'CTU', 'Code': 28},
            # {'city': '沧源', 'ThreeCode': 'CWJ', 'Code': 21741},
            {'city': '常州', 'ThreeCode': 'CZX', 'Code': 213},
            # {'city': '池州', 'ThreeCode': 'JUH', 'Code': 218},
            # {'city': '大同', 'ThreeCode': 'DAT', 'Code': 136},
            # {'city': '达州', 'ThreeCode': 'DAX', 'Code': 234},
            # {'city': '稻城', 'ThreeCode': 'DCY', 'Code': 1222},
            # {'city': '丹东', 'ThreeCode': 'DDG', 'Code': 221},
            # {'city': '迪庆', 'ThreeCode': 'DIG', 'Code': 93},
            {'city': '大连', 'ThreeCode': 'DLC', 'Code': 6},
            # {'city': '大理', 'ThreeCode': 'DLU', 'Code': 36},
            # {'city': '敦煌', 'ThreeCode': 'DNH', 'Code': 11},
            # {'city': '东营', 'ThreeCode': 'DOY', 'Code': 236},
            # {'city': '大庆', 'ThreeCode': 'DQA', 'Code': 231},
            # {'city': '德令哈', 'ThreeCode': 'HXD', 'Code': 2542},
            # {'city': '鄂尔多斯', 'ThreeCode': 'DSN', 'Code': 3976},
            # {'city': '额济纳旗', 'ThreeCode': 'EJN', 'Code': 21339},
            # {'city': '恩施', 'ThreeCode': 'ENH', 'Code': 245},
            # {'city': '二连浩特', 'ThreeCode': 'ERL', 'Code': 7626},
            {'city': '福州', 'ThreeCode': 'FOC', 'Code': 258},
            # {'city': '阜阳', 'ThreeCode': 'FUG', 'Code': 257},
            # {'city': '抚远', 'ThreeCode': 'FYJ', 'Code': 21943},
            # {'city': '富蕴', 'ThreeCode': 'FYN', 'Code': 255},
            {'city': '广州', 'ThreeCode': 'CAN', 'Code': 32},
            # {'city': '果洛', 'ThreeCode': 'GMQ', 'Code': 21862},
            # {'city': '格尔木', 'ThreeCode': 'GOQ', 'Code': 132},
            # {'city': '广元', 'ThreeCode': 'GYS', 'Code': 267},
            # {'city': '固原', 'ThreeCode': 'GYU', 'Code': 321},
            # {'city': '赣州', 'ThreeCode': 'KOW', 'Code': 268},
            {'city': '贵阳', 'ThreeCode': 'KWE', 'Code': 38},
            # {'city': '桂林', 'ThreeCode': 'KWL', 'Code': 33},
            # {'city': '红原', 'ThreeCode': 'AHJ', 'Code': 7835},
            {'city': '海口', 'ThreeCode': 'HAK', 'Code': 42},
            # {'city': '河池', 'ThreeCode': 'HCJ', 'Code': 3969},
            # {'city': '邯郸', 'ThreeCode': 'HDG', 'Code': 275},
            # {'city': '黑河', 'ThreeCode': 'HEK', 'Code': 281},
            # {'city': '呼和浩特', 'ThreeCode': 'HET', 'Code': 103},
            {'city': '合肥', 'ThreeCode': 'HFE', 'Code': 278},
            {'city': '杭州', 'ThreeCode': 'HGH', 'Code': 17},
            # {'city': '淮安', 'ThreeCode': 'HIA', 'Code': 577},
            # {'city': '怀化', 'ThreeCode': 'HJJ', 'Code': 282},
            # {'city': '海拉尔', 'ThreeCode': 'HLD', 'Code': 142},
            # {'city': '哈密', 'ThreeCode': 'HMI', 'Code': 21395},
            # {'city': '衡阳', 'ThreeCode': 'HNY', 'Code': 297},
            {'city': '哈尔滨', 'ThreeCode': 'HRB', 'Code': 5},
            # {'city': '和田', 'ThreeCode': 'HTN', 'Code': 294},
            # {'city': '花土沟', 'ThreeCode': 'HTT', 'Code': 83679},
            # {'city': '霍林郭勒', 'ThreeCode': 'HUO', 'Code': 21091},
            {'city': '惠州', 'ThreeCode': 'HUZ', 'Code': 299},
            # {'city': '汉中', 'ThreeCode': 'HZG', 'Code': 129},
            # {'city': '黄山', 'ThreeCode': 'TXN', 'Code': 23},
            # {'city': '呼伦贝尔', 'ThreeCode': 'XRQ', 'Code': 4255},
            # {'city': '中国嘉义', 'ThreeCode': 'CYI', 'Code': 5152},
            # {'city': '景德镇', 'ThreeCode': 'JDZ', 'Code': 305},
            # {'city': '加格达奇', 'ThreeCode': 'JGD', 'Code': 1143},
            # {'city': '嘉峪关', 'ThreeCode': 'JGN', 'Code': 326},
            # {'city': '井冈山', 'ThreeCode': 'JGS', 'Code': 307},
            # {'city': '金昌', 'ThreeCode': 'JIC', 'Code': 1158},
            # {'city': '九江', 'ThreeCode': 'JIU', 'Code': 24},
            # {'city': '荆门', 'ThreeCode': 'JM1', 'Code': 1121},
            # {'city': '佳木斯', 'ThreeCode': 'JMU', 'Code': 317},
            # {'city': '济宁', 'ThreeCode': 'JNG', 'Code': 318},
            # {'city': '锦州', 'ThreeCode': 'JNZ', 'Code': 327},
            # {'city': '建三江', 'ThreeCode': 'JSJ', 'Code': 1623},
            # {'city': '鸡西', 'ThreeCode': 'JXA', 'Code': 157},
            # {'city': '九寨沟', 'ThreeCode': 'JZH', 'Code': 91},
            # {'city': '中国金门', 'ThreeCode': 'KNH', 'Code': 7203},
            # {'city': '揭阳', 'ThreeCode': 'SWA', 'Code': 956},
            {'city': '济南', 'ThreeCode': 'TNA', 'Code': 144},
            # {'city': '库车', 'ThreeCode': 'KCA', 'Code': 329},
            # {'city': '康定', 'ThreeCode': 'KGT', 'Code': 4130},
            # {'city': '喀什', 'ThreeCode': 'KHG', 'Code': 21358},
            # {'city': '凯里', 'ThreeCode': 'KJH', 'Code': 333},
            {'city': '昆明', 'ThreeCode': 'KMG', 'Code': 34},
            # {'city': '库尔勒', 'ThreeCode': 'KRL', 'Code': 330},
            # {'city': '克拉玛依', 'ThreeCode': 'KRY', 'Code': 166},
            # {'city': '黎平', 'ThreeCode': 'HZH', 'Code': 3852},
            # {'city': '澜沧', 'ThreeCode': 'JMJ', 'Code': 21596},
            # {'city': '龙岩', 'ThreeCode': 'LCX', 'Code': 348},
            # {'city': '临汾', 'ThreeCode': 'LFQ', 'Code': 139},
            {'city': '兰州', 'ThreeCode': 'LHW', 'Code': 100},
            # {'city': '丽江', 'ThreeCode': 'LJG', 'Code': 37},
            # {'city': '荔波', 'ThreeCode': 'LLB', 'Code': 1708},
            # {'city': '吕梁', 'ThreeCode': 'LLV', 'Code': 7631},
            # {'city': '临沧', 'ThreeCode': 'LNJ', 'Code': 1236},
            # {'city': '陇南', 'ThreeCode': 'LNL', 'Code': 7707},
            # {'city': '六盘水', 'ThreeCode': 'LPF', 'Code': 605},
            # {'city': '拉萨', 'ThreeCode': 'LXA', 'Code': 41},
            # {'city': '洛阳', 'ThreeCode': 'LYA', 'Code': 350},
            # {'city': '连云港', 'ThreeCode': 'LYG', 'Code': 353},
            # {'city': '临沂', 'ThreeCode': 'LYI', 'Code': 569},
            # {'city': '柳州', 'ThreeCode': 'LZH', 'Code': 354},
            # {'city': '泸州', 'ThreeCode': 'LZO', 'Code': 355},
            # {'city': '林芝', 'ThreeCode': 'LZY', 'Code': 108},
            # {'city': '芒市', 'ThreeCode': 'LUM', 'Code': 3997},
            # {'city': '牡丹江', 'ThreeCode': 'MDG', 'Code': 150},
            # {'city': '中国马祖', 'ThreeCode': 'MFK', 'Code': 7808},
            # {'city': '绵阳', 'ThreeCode': 'MIG', 'Code': 370},
            # {'city': '梅州', 'ThreeCode': 'MXZ', 'Code': 3053},
            # {'city': '中国马公', 'ThreeCode': 'MZG', 'Code': 5383},
            # {'city': '满洲里', 'ThreeCode': 'NZH', 'Code': 1083},
            # {'city': '漠河', 'ThreeCode': 'OHE', 'Code': 155},
            {'city': '南昌', 'ThreeCode': 'KHN', 'Code': 376},
            # {'city': '中国南竿', 'ThreeCode': 'LZN', 'Code': 91804},
            # {'city': '南充', 'ThreeCode': 'NAO', 'Code': 377},
            {'city': '宁波', 'ThreeCode': 'NGB', 'Code': 375},
            {'city': '南京', 'ThreeCode': 'NKG', 'Code': 12},
            # {'city': '宁蒗', 'ThreeCode': 'NLH', 'Code': 1161},
            {'city': '南宁', 'ThreeCode': 'NNG', 'Code': 380},
            # {'city': '南阳', 'ThreeCode': 'NNY', 'Code': 385},
            {'city': '南通', 'ThreeCode': 'NTG', 'Code': 82},
            # {'city': '攀枝花', 'ThreeCode': 'PZI', 'Code': 1097},
            # {'city': '普洱', 'ThreeCode': 'SYM', 'Code': 3996},
            # {'city': '琼海', 'ThreeCode': 'BAR', 'Code': 52},
            # {'city': '秦皇岛', 'ThreeCode': 'BPE', 'Code': 147},
            # {'city': '祁连', 'ThreeCode': 'HBQ', 'Code': 20892},
            # {'city': '且末', 'ThreeCode': 'IQM', 'Code': 399},
            # {'city': '庆阳', 'ThreeCode': 'IQN', 'Code': 404},
            # {'city': '黔江', 'ThreeCode': 'JIQ', 'Code': 7708},
            {'city': '泉州', 'ThreeCode': 'JJN', 'Code': 406},
            # {'city': '衢州', 'ThreeCode': 'JUZ', 'Code': 407},
            # {'city': '齐齐哈尔', 'ThreeCode': 'NDG', 'Code': 149},
            {'city': '青岛', 'ThreeCode': 'TAO', 'Code': 7},
            # {'city': '日照', 'ThreeCode': 'RIZ', 'Code': 1106},
            # {'city': '日喀则', 'ThreeCode': 'RKZ', 'Code': 92},
            # {'city': '若羌', 'ThreeCode': 'RQA', 'Code': 21737},
            # {'city': '神农架', 'ThreeCode': 'HPG', 'Code': 657},
            # {'city': '莎车', 'ThreeCode': 'QSZ', 'Code': 21827},
            {'city': '上海', 'ThreeCode': 'SHA', 'Code': 2},
            {'city': '沈阳', 'ThreeCode': 'SHE', 'Code': 451},
            # {'city': '石河子', 'ThreeCode': 'SHF', 'Code': 426},
            {'city': '石家庄', 'ThreeCode': 'SJW', 'Code': 428},
            # {'city': '上饶', 'ThreeCode': 'SQD', 'Code': 411},
            # {'city': '三明', 'ThreeCode': 'SQJ', 'Code': 437},
            # {'city': '三亚', 'ThreeCode': 'SYX', 'Code': 43},
            {'city': '深圳', 'ThreeCode': 'SZX', 'Code': 30},
            # {'city': '十堰', 'ThreeCode': 'WDS', 'Code': 452},
            # {'city': '邵阳', 'ThreeCode': 'WGN', 'Code': 1111},
            # {'city': '松原', 'ThreeCode': 'YSQ', 'Code': 1303},
            {'city': '台州', 'ThreeCode': 'HYN', 'Code': 578},
            # {'city': '塔城', 'ThreeCode': 'TCG', 'Code': 455},
            # {'city': '腾冲', 'ThreeCode': 'TCZ', 'Code': 1819},
            # {'city': '铜仁', 'ThreeCode': 'TEN', 'Code': 1227},
            # {'city': '通辽', 'ThreeCode': 'TGO', 'Code': 458},
            # {'city': '天水', 'ThreeCode': 'THQ', 'Code': 464},
            # {'city': '吐鲁番', 'ThreeCode': 'TLQ', 'Code': 21811},
            # {'city': '通化', 'ThreeCode': 'TNH', 'Code': 456},
            {'city': '天津', 'ThreeCode': 'TSN', 'Code': 3},
            # {'city': '唐山', 'ThreeCode': 'TVS', 'Code': 468},
            {'city': '太原', 'ThreeCode': 'TYN', 'Code': 105},
            # {'city': '五大连池', 'ThreeCode': 'DTU', 'Code': 473},
            # {'city': '乌兰浩特', 'ThreeCode': 'HLH', 'Code': 484},
            # {'city': '乌兰察布', 'ThreeCode': 'UCB', 'Code': 7518},
            {'city': '乌鲁木齐', 'ThreeCode': 'URC', 'Code': 39},
            # {'city': '潍坊', 'ThreeCode': 'WEF', 'Code': 475},
            # {'city': '威海', 'ThreeCode': 'WEH', 'Code': 479},
            # {'city': '文山', 'ThreeCode': 'WNH', 'Code': 20963},
            {'city': '温州', 'ThreeCode': 'WNZ', 'Code': 491},
            # {'city': '乌海', 'ThreeCode': 'WUA', 'Code': 1133},
            {'city': '武汉', 'ThreeCode': 'WUH', 'Code': 477},
            # {'city': '武夷山', 'ThreeCode': 'WUS', 'Code': 26},
            {'city': '无锡', 'ThreeCode': 'WUX', 'Code': 13},
            # {'city': '梧州', 'ThreeCode': 'WUZ', 'Code': 492},
            # {'city': '万州', 'ThreeCode': 'WXN', 'Code': 487},
            # {'city': '乌拉特中旗', 'ThreeCode': 'WZQ', 'Code': 21184},
            # {'city': '巫山', 'ThreeCode': 'WSK', 'Code': 684995},
            # {'city': '兴义', 'ThreeCode': 'ACX', 'Code': 1139},
            # {'city': '夏河', 'ThreeCode': 'GXH', 'Code': 497},
            # {'city': '西双版纳', 'ThreeCode': 'JHG', 'Code': 35},
            # {'city': '新源', 'ThreeCode': 'NLT', 'Code': 3360},
            {'city': '西安', 'ThreeCode': 'SIA', 'Code': 10},
            # {'city': '忻州', 'ThreeCode': 'WUT', 'Code': 513},
            # {'city': '信阳', 'ThreeCode': 'XAI', 'Code': 510},
            # {'city': '襄阳', 'ThreeCode': 'XFN', 'Code': 496},
            # {'city': '西昌', 'ThreeCode': 'XIC', 'Code': 494},
            # {'city': '锡林浩特', 'ThreeCode': 'XIL', 'Code': 500},
            {'city': '厦门', 'ThreeCode': 'XMN', 'Code': 25},
            # {'city': '西宁', 'ThreeCode': 'XNN', 'Code': 124},
            {'city': '徐州', 'ThreeCode': 'XUZ', 'Code': 512},
            # {'city': '延安', 'ThreeCode': 'ENY', 'Code': 110},
            # {'city': '银川', 'ThreeCode': 'INC', 'Code': 99},
            # {'city': '伊春', 'ThreeCode': 'LDS', 'Code': 517},
            # {'city': '永州', 'ThreeCode': 'LLF', 'Code': 970},
            # {'city': '榆林', 'ThreeCode': 'UYN', 'Code': 527},
            # {'city': '宜宾', 'ThreeCode': 'YBP', 'Code': 514},
            # {'city': '运城', 'ThreeCode': 'YCU', 'Code': 140},
            # {'city': '宜春', 'ThreeCode': 'YIC', 'Code': 518},
            # {'city': '宜昌', 'ThreeCode': 'YIH', 'Code': 515},
            # {'city': '伊宁', 'ThreeCode': 'YIN', 'Code': 529},
            # {'city': '义乌', 'ThreeCode': 'YIW', 'Code': 536},
            # {'city': '营口', 'ThreeCode': 'YKH', 'Code': 1300},
            # {'city': '延吉', 'ThreeCode': 'YNJ', 'Code': 523},
            {'city': '烟台', 'ThreeCode': 'YNT', 'Code': 533},
            # {'city': '盐城', 'ThreeCode': 'YNZ', 'Code': 1200},
            # {'city': '扬州', 'ThreeCode': 'YTY', 'Code': 15},
            # {'city': '玉树', 'ThreeCode': 'YUS', 'Code': 21114},
            # {'city': '岳阳', 'ThreeCode': 'YYA', 'Code': 539},
            {'city': '郑州', 'ThreeCode': 'CGO', 'Code': 559},
            # {'city': '张家界', 'ThreeCode': 'DYG', 'Code': 27},
            {'city': '舟山', 'ThreeCode': 'HSN', 'Code': 19},
            # {'city': '扎兰屯', 'ThreeCode': 'NZL', 'Code': 1135},
            # {'city': '张掖', 'ThreeCode': 'YZY', 'Code': 663},
            # {'city': '昭通', 'ThreeCode': 'ZAT', 'Code': 555},
            # {'city': '湛江', 'ThreeCode': 'ZHA', 'Code': 547},
            # {'city': '中卫', 'ThreeCode': 'ZHY', 'Code': 556},
            # {'city': '张家口', 'ThreeCode': 'ZQZ', 'Code': 550},
            {'city': '珠海', 'ThreeCode': 'ZUH', 'Code': 31},
            # {'city': '遵义', 'ThreeCode': 'ZYI', 'Code': 558}
        ]

        return item


'''      北京，上海，宁波，杭州，广州，深圳  '''
